name: fastapi-mongo-starter
services:
    - name: api
      github:
          branch: main
          repo: sayedsamin/cencad-fastapi
      build_command: ""
      run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
      envs:
          - key: DEBUG
            scope: RUN_AND_BUILD_TIME
            value: "false"
          - key: JWT_SECRET_KEY
            scope: RUN_AND_BUILD_TIME
            value: ${JWT_SECRET_KEY}
          - key: JWT_ALGORITHM
            scope: RUN_AND_BUILD_TIME
            value: HS256
          - key: JWT_EXPIRATION_HOURS
            scope: RUN_AND_BUILD_TIME
            value: "24"
          - key: MONGODB_URL
            scope: RUN_AND_BUILD_TIME
            value: ${MONGODB_URL}
          - key: MONGODB_DB
            scope: RUN_AND_BUILD_TIME
            value: proddb
          - key: MONGODB_USERNAME
            scope: RUN_AND_BUILD_TIME
            value: ${MONGODB_USERNAME}
          - key: MONGODB_PASSWORD
            scope: RUN_AND_BUILD_TIME
            value: ${MONGODB_PASSWORD}
      http_port: 8080
      instance_count: 2
      instance_size_slug: basic-xs
      log_destinations:
          - name: api_logs
            papertrail:
                token: ${PAPERTRAIL_TOKEN}
      source_dir: /
databases:
    - engine: MONGODB
      name: prod-mongodb
      version: "7.0"
      production: true
      envs:
          - key: MONGODB_URL
            value: mongodb+srv://${db-user}:${db-password}@${db-host}
static_sites: []
jobs: []
